# Generated by Django 5.1.3 on 2025-02-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('select gender', 'Select gender'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='select gender', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('grade', models.CharField(choices=[('select grade', 'Select Grade'), ('grade 9', 'Grade 9'), ('grade 10', 'Grade 10'), ('grade 11', 'Grade 11'), ('grade 12', 'Grade 12')], default='select grade', max_length=50)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='students-photos/')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15, unique=True)),
                ('parent_email', models.EmailField(max_length=254, unique=True)),
                ('relationship', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group')),
            ],
        ),
    ]
