# Generated by Django 5.1.3 on 2025-02-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='teachers-photos/')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('position', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('employment_type', models.CharField(choices=[('select employment type', 'Select employment type'), ('full time', 'Full time'), ('part time', 'Part time'), ('contract', 'Contract')], default='select employment type', max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='departments.department')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='subjects.subject')),
            ],
        ),
    ]
