# Generated by Django 5.1.3 on 2025-02-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('select grade', 'Select Grade'), ('grade 9', 'Grade 9'), ('grade 10', 'Grade 10'), ('grade 11', 'Grade 11'), ('grade 12', 'Grade 12')], default='select grade', max_length=50)),
                ('schedule', models.CharField(choices=[('select schedule', 'Select schedule'), ('morning session', 'Morning session'), ('afternoon session', 'Afternoon session'), ('evening session', 'Evening session')], default='select schedule', max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('max_students', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('subjects', models.ManyToManyField(related_name='groups', to='subjects.subject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='teachers.teacher')),
            ],
        ),
    ]
